### ISSUE TITLE
Please stop using backslashes in file paths.

### ISSUE THREAD

**Issue by dries007** [SmithsModding/Weaponry#2]
Java converts forward slashes into backslashes on windows, but it does not do the opposite on linux. Now my filebrowser looks like this:
https://dries007.net/screenshots/2015-09-20_18-50-23.png

**Comment by marchermans** [comment]
I noticed it. A interval persoon has this fixed. I will see if I can get you a fixed version with out the backslashes. Give a bit of time.

**Comment by marchermans** [comment]
Hello we fixed the issue on our testing server. Could you check if this nightly build fixed the issue for you: http://mavenrepo.armory.orionminecraft.com/com/Orion/Armory/Armory/1.0.1.3-244-SNAPSHOT/
You will not need to update Weaponry (and World, if you have that instralled) just Armory Itself. 

If you find no issues could you report that back, i will release a new version then.

**Comment by dries007** [comment]
Seems to work nicely, thanks.

**Comment by marchermans** [comment]
Okey i will release a new version for the rest then :package:
