### ISSUE TITLE
Crash with latest version (1.3.0-56).

### ISSUE THREAD

**Issue by Liiw** [SmithsModding/Weaponry#3]
Hello!

I have experienced a client crash with the latest version of Armory-Weaponry (1.3.0-56). I am inlcuding the crash log regarding this. The last version (1.3.0-53) does not crash. I am currently reverting to that.

[crash-2017-03-02_20.28.31-client.txt](https://github.com/SmithsGaming/Weaponry/files/814852/crash-2017-03-02_20.28.31-client.txt)

**Comment by vrork** [comment]
Same here
https://gist.github.com/vrork/0a4cc3fdf2496655f5ec217e485f4ae7

**Comment by marchermans** [comment]
Should have fixed it. 
Tried to load a dynamic model from file which files für certain TCon addons.

A new build is on the way.
